### ISSUE TITLE
JSON.stringify cannot serialize cyclic structures.

### ISSUE THREAD

**Issue by PublicParadise** [jaysoo/react-native-parallax-scroll-view#23]
### Steps

- Build and run the `ListView` example
- Activate `Inspector`
- Click into the upper half of the header (i.e. on the word "World")

![screen shot 2016-03-20 at 9 07 24 pm](https://cloud.githubusercontent.com/assets/2541332/13910479/155d64c2-eee0-11e5-9b3e-4345330a9adc.png)

**Comment by PublicParadise** [comment]
I suspect the area that you need to hit is the `renderFixedHeader` area.

**Comment by jaysoo** [comment]
@PublicParadise Sorry for the delay. The problem was that the interpolated style value of sticky header caused the inspector code to break. I'll have to double-check what's happening on React Native's end, but for now I've added an override of `toJSON` that simply returns the current interpolated value.

**Comment by cho-is** [comment]
this is happening for me
